# Generated by Django 2.1 on 2018-10-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20181005_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='down_votes_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='up_votes_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
