# Generated by Django 2.1 on 2018-10-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20181005_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='down_votes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='up_votes_count',
            field=models.IntegerField(default=0),
        ),
    ]
